### ISSUE TITLE
Stackblitz URL gives multiple error

### ISSUE THREAD

**Issue by mohatasuraj** [ManpreetSingh80/travel-marker#22]
Hi Manpreet
Getting this following issue in Stackblitz, even after adding
<script src="https://unpkg.com/travel-marker/dist/travel-marker.umd.js"></script>
to index.html tag

![image](https://user-images.githubusercontent.com/14251390/76285223-3aa20f00-62c5-11ea-9d7a-582643865f99.png)

Need help.Please guide

**Comment by ManpreetSingh80** [comment]
It's fixed now.

**Comment by mohatasuraj** [comment]
yeah it's fixed.
Thank You Manpreet :-)
