### ISSUE TITLE
Unable to pass more than 23 waypoints

### ISSUE THREAD

**Issue by tag8ashok** [ManpreetSingh80/travel-marker#4]
I retriving lat,long from an api and passing to waypoints its response is QUERY OVER LIMIT

**Comment by ManpreetSingh80** [comment]
Hi @tag8ashok,

The Directions API from Google only allow upto 23 waypoints(Premium Plan)
[https://developers.google.com/maps/documentation/javascript/directions](https://developers.google.com/maps/documentation/javascript/directions)
