### ISSUE TITLE
Stackblitz example is broken

### ISSUE THREAD

**Issue by weijyewang** [ManpreetSingh80/travel-marker#6]
The Stackblitz example is broken: https://stackblitz.com/edit/travel-marker-angular-agm

**Comment by ManpreetSingh80** [comment]
Hi @weijyewang,

Thanks for taking interest in this library.

Unfortunately, Google no longer provides a free tier for directions API. Hence, the example was broken as it was using Directions service. It will still work if an API key is provided with Directions API enabled.

Meanwhile, I am using pre-calculated locations now to fix the demo. [It is working again now](https://stackblitz.com/edit/travel-marker-angular-agm)

**Comment by weijyewang** [comment]
Cheers. The demo example is working. A big thanks for this awesome library!
