### ISSUE TITLE
Can't able to play marker on path

### ISSUE THREAD

**Issue by ghost** [ManpreetSingh80/travel-marker#9]
Script was working fine before.
But from yesterday, it stops working.

Issue description:
On page load, a map marker is not playing on path and also that features of play, pause, reset, etc not working.

In console, getting below error.

Please insert valid location Array
Uncaught TypeError: Cannot read property 'play' of null
    at TravelMarker.play (travel-marker.umd.js:969)
    at play ((index):168)

**Comment by ManpreetSingh80** [comment]
Hi,

The problem was in getting the location array from Google Polyline. I changed the

```
line.getPath().j;
```

to

```
line.getPath().getArray();
```

Even examples are working fine now.

**Comment by ghost** [comment]
Yes. It's working fine now.
Thank you so much for your help.
